server:
  port: 8000
mybatis:
  configuration:
    cache-enabled: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiuyunedu.sky.bean
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clouddb01?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: microservicecloud-provider-dept
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
info:
  app.name: ${spring.application.name}
  compnay.name: www.jiuyun.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
---
server:
  port: 8001
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clouddb02?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true
  application:
    name: microservicecloud-provider-dept-dev
---
server:
  port: 8002
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clouddb03?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true
  application:
    name: microservicecloud-provider-dept-test